language: java

os:
  - linux

jdk:
  - oraclejdk8

# before_install is used to provide a workaround for buffer overflow issues with OpenJDK versions of java as per:
#    https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165135711
before_install:
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts

  - wget http://apache.claz.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  - tar zxvf apache-maven-3.3.9-bin.tar.gz
  - chmod +x apache-maven-3.3.9/bin/mvn
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$PWD/apache-maven-3.3.9/bin:${PATH}
  - hash -r

before_script:
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$PWD/apache-maven-3.3.9/bin:${PATH}
  - hash -r

install: mvn clean install
